language: r
dist: trusty
sudo: true
group: beta
cache: packages

os:
  - linux

apt_packages:
  - libgeos-dev
  - libgeos-c1    
  - curl
  - libssh2-1-dev
  - qpdf 

r_binary_packages:
  - rgdal
  - rgeos

before_script:
  - chmod +x ./Makefile

script:
  - make build
  - make deploy
