language: r
dist: trusty
sudo: true
group: beta
cache: packages

os:
  - linux

apt_packages:
  - libgeos-dev
  - libgeos-c1
  - libgdal-dev
  - libproj-dev
  - curl
  - libssh2-1-dev
  - qpdf 

before_install: 
  - sudo apt-get --yes --force-yes update -qq
  - tlmgr install makecell float hyperref
  - sudo apt-get --yes --force-yes remove pandoc pandoc-citeproc
  - sudo wget https://github.com/jgm/pandoc/releases/download/1.18/pandoc-1.18-1-amd64.deb -O ~/pandoc.deb
  - sudo dpkg -i ~/pandoc.deb

r_binary_packages:
  - rgdal
  - rgeos

before_script:
  - chmod +x ./Makefile

script:
  - make build
  - make deploy
